substitutions:
  device_name: nedorachio
  friendly_name: Nedorachio Irrigation Controller

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  core: !include packages/01-core.yaml
