substitutions:
  device_name: nedorachio
  friendly_name: Nedorachio Irrigation Controller

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}
  platformio_options:
    lib_deps:
      - bblanchon/ArduinoJson@^7.2.0

esp32:
  board: esp32dev
  framework:
    type: arduino

external_components:
  - source:
      type: local
      path: components

packages:
  core: !include packages/01-core.yaml
  component: !include packages/10-nedorachio-component.yaml
  config: !include packages/11-config-profile.yaml
