substitutions:
  device_name: nedorachio
  friendly_name: Nedorachio Irrigation Controller

esphome:
  name: ${device_name}
  friendly_name: ${friendly_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

packages:
  core: !include packages/01-core.yaml
  zones: !include packages/02-zones.yaml
  sensors: !include packages/03-sensors.yaml
  tunables: !include packages/04-tunables.yaml
